title: Product Radio
description: Tuning into AI & Product Strategy
url: "https://maharshi-adiraju.github.io/"   # replace with your GitHub Pages URL
baseurl: "/productradio"            # the repository name
theme: minima
header_pages:
 
  - signal-grid.md
  - agentic-ai.md
  - blog-posts.md
